# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.7

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /home/well/cmake/bin/cmake

# The command to remove a file.
RM = /home/well/cmake/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/well/Desktop/ansV2

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/well/Desktop/ansV2

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/home/well/cmake/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/home/well/cmake/bin/cmake-gui -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/well/Desktop/ansV2/CMakeFiles /home/well/Desktop/ansV2/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/well/Desktop/ansV2/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named ansV2

# Build rule for target.
ansV2: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ansV2
.PHONY : ansV2

# fast build rule for target.
ansV2/fast:
	$(MAKE) -f CMakeFiles/ansV2.dir/build.make CMakeFiles/ansV2.dir/build
.PHONY : ansV2/fast

src/ans.o: src/ans.cpp.o

.PHONY : src/ans.o

# target to build an object file
src/ans.cpp.o:
	$(MAKE) -f CMakeFiles/ansV2.dir/build.make CMakeFiles/ansV2.dir/src/ans.cpp.o
.PHONY : src/ans.cpp.o

src/ans.i: src/ans.cpp.i

.PHONY : src/ans.i

# target to preprocess a source file
src/ans.cpp.i:
	$(MAKE) -f CMakeFiles/ansV2.dir/build.make CMakeFiles/ansV2.dir/src/ans.cpp.i
.PHONY : src/ans.cpp.i

src/ans.s: src/ans.cpp.s

.PHONY : src/ans.s

# target to generate assembly for a file
src/ans.cpp.s:
	$(MAKE) -f CMakeFiles/ansV2.dir/build.make CMakeFiles/ansV2.dir/src/ans.cpp.s
.PHONY : src/ans.cpp.s

src/ans_Config.o: src/ans_Config.cpp.o

.PHONY : src/ans_Config.o

# target to build an object file
src/ans_Config.cpp.o:
	$(MAKE) -f CMakeFiles/ansV2.dir/build.make CMakeFiles/ansV2.dir/src/ans_Config.cpp.o
.PHONY : src/ans_Config.cpp.o

src/ans_Config.i: src/ans_Config.cpp.i

.PHONY : src/ans_Config.i

# target to preprocess a source file
src/ans_Config.cpp.i:
	$(MAKE) -f CMakeFiles/ansV2.dir/build.make CMakeFiles/ansV2.dir/src/ans_Config.cpp.i
.PHONY : src/ans_Config.cpp.i

src/ans_Config.s: src/ans_Config.cpp.s

.PHONY : src/ans_Config.s

# target to generate assembly for a file
src/ans_Config.cpp.s:
	$(MAKE) -f CMakeFiles/ansV2.dir/build.make CMakeFiles/ansV2.dir/src/ans_Config.cpp.s
.PHONY : src/ans_Config.cpp.s

src/ans_File.o: src/ans_File.cpp.o

.PHONY : src/ans_File.o

# target to build an object file
src/ans_File.cpp.o:
	$(MAKE) -f CMakeFiles/ansV2.dir/build.make CMakeFiles/ansV2.dir/src/ans_File.cpp.o
.PHONY : src/ans_File.cpp.o

src/ans_File.i: src/ans_File.cpp.i

.PHONY : src/ans_File.i

# target to preprocess a source file
src/ans_File.cpp.i:
	$(MAKE) -f CMakeFiles/ansV2.dir/build.make CMakeFiles/ansV2.dir/src/ans_File.cpp.i
.PHONY : src/ans_File.cpp.i

src/ans_File.s: src/ans_File.cpp.s

.PHONY : src/ans_File.s

# target to generate assembly for a file
src/ans_File.cpp.s:
	$(MAKE) -f CMakeFiles/ansV2.dir/build.make CMakeFiles/ansV2.dir/src/ans_File.cpp.s
.PHONY : src/ans_File.cpp.s

src/ans_Log.o: src/ans_Log.cpp.o

.PHONY : src/ans_Log.o

# target to build an object file
src/ans_Log.cpp.o:
	$(MAKE) -f CMakeFiles/ansV2.dir/build.make CMakeFiles/ansV2.dir/src/ans_Log.cpp.o
.PHONY : src/ans_Log.cpp.o

src/ans_Log.i: src/ans_Log.cpp.i

.PHONY : src/ans_Log.i

# target to preprocess a source file
src/ans_Log.cpp.i:
	$(MAKE) -f CMakeFiles/ansV2.dir/build.make CMakeFiles/ansV2.dir/src/ans_Log.cpp.i
.PHONY : src/ans_Log.cpp.i

src/ans_Log.s: src/ans_Log.cpp.s

.PHONY : src/ans_Log.s

# target to generate assembly for a file
src/ans_Log.cpp.s:
	$(MAKE) -f CMakeFiles/ansV2.dir/build.make CMakeFiles/ansV2.dir/src/ans_Log.cpp.s
.PHONY : src/ans_Log.cpp.s

src/main.o: src/main.cpp.o

.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) -f CMakeFiles/ansV2.dir/build.make CMakeFiles/ansV2.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) -f CMakeFiles/ansV2.dir/build.make CMakeFiles/ansV2.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) -f CMakeFiles/ansV2.dir/build.make CMakeFiles/ansV2.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... ansV2"
	@echo "... src/ans.o"
	@echo "... src/ans.i"
	@echo "... src/ans.s"
	@echo "... src/ans_Config.o"
	@echo "... src/ans_Config.i"
	@echo "... src/ans_Config.s"
	@echo "... src/ans_File.o"
	@echo "... src/ans_File.i"
	@echo "... src/ans_File.s"
	@echo "... src/ans_Log.o"
	@echo "... src/ans_Log.i"
	@echo "... src/ans_Log.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

